version: '3'
services:

  discovery:
    image: namanlakhani/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"

  gateway:
    image: namanlakhani/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      - discovery
    links:
      - discovery:discovery
      
  user-service:
    image: namanlakhani/user-service:latest
    container_name: user-service
    ports:
      - "8013:2222"
    depends_on:
      - discovery
      - mysql
    links:
      - discovery:discovery

  parenttask-service:
    image: namanlakhani/parenttask-service:latest
    container_name: parenttask-service
    ports:
      - "8010:2222"
    depends_on:
      - discovery
      - mysql
    links:
      - discovery:discovery

  project-service:
    image: namanlakhani/project-service:latest
    container_name: project-service
    ports:
      - "8011:2222"
    depends_on:
      - discovery
      - user-service
      - mysql
    links:
      - discovery:discovery
      - user-service:user-service

  task-service:
    image: namanlakhani/task-service:latest
    container_name: task-service
    ports:
      - "8012:2222"
    depends_on:
      - discovery
      - user-service
      - project-service
      - parenttask-service
      - mysql
    links:
      - discovery:discovery
      - user-service:user-service
      - project-service:project-service
      - parenttask-service:parenttask-service

  mysql:
      container_name: mysql-docker
      image: mysql/mysql-server:latest
      environment:
        MYSQL_DATABASE: projectmanager
        MYSQL_ROOT_PASSWORD: pass@word1
        MYSQL_ROOT_HOST: '%'
      ports:
        - "3306:3306"
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 20s
        retries: 20
      restart: always